<?xml version="1.0" encoding="UTF-8" ?>
<testsuites disabled="0" errors="0" failures="33" tests="251" time="986.56">
 <testsuite name="Hybrent Login Module" timestamp="2019-10-25T19:20:03" hostname="localhost" time="23.246" errors="0" tests="3" skipped="0" disabled="0" failures="2">
  <testcase classname="Hybrent Login Module" name="Login: Try login without any credentials." time="6.214">
   <failure type="exception" message="Error: Error while waiting for Protractor to sync with the page: &quot;both angularJS testability and angular testability are undefined.  This could be either because this is a non-angular page or because your test involves client-side navigation, which can interfere with Protractor&apos;s bootstrapping.  See http://git.io/v4gXM for details&quot;"><![CDATA[Error: Error while waiting for Protractor to sync with the page: "both angularJS testability and angular testability are undefined.  This could be either because this is a non-angular page or because your test involves client-side navigation, which can interfere with Protractor's bootstrapping.  See http://git.io/v4gXM for details"
    at runWaitForAngularScript.then (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\browser.js:463:23)
    at ManagedPromise.invokeCallback_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
    at process._tickCallback (internal/process/next_tick.js:68:7)Error
    at ElementArrayFinder.applyAction_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:459:27)
    at ElementArrayFinder.(anonymous function).args [as click] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:91:29)
    at ElementFinder.(anonymous function).args [as click] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:831:22)
    at Suite.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\DME\Start_new_claim.js:51:32)
    at addSpecsToSuite (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
    at Env.describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
    at describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
    at Object.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\DME\Start_new_claim.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)]]>
   </failure>
   <failure type="exception" message="Failed: Error while waiting for Protractor to sync with the page: &quot;both angularJS testability and angular testability are undefined.  This could be either because this is a non-angular page or because your test involves client-side navigation, which can interfere with Protractor&apos;s bootstrapping.  See http://git.io/v4gXM for details&quot;"><![CDATA[Error: Error while waiting for Protractor to sync with the page: "both angularJS testability and angular testability are undefined.  This could be either because this is a non-angular page or because your test involves client-side navigation, which can interfere with Protractor's bootstrapping.  See http://git.io/v4gXM for details"
    at runWaitForAngularScript.then (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\browser.js:463:23)
    at ManagedPromise.invokeCallback_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: <anonymous>
    at pollCondition (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2195:19)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2191:7
    at new ManagedPromise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
    at ControlFlow.promise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2190:22
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2974:25)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
From: Task: <anonymous wait>
    at scheduleWait (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2188:20)
    at ControlFlow.wait (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2517:12)
    at thenableWebDriverProxy.wait (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:934:29)
    at run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\browser.js:59:33)
    at ProtractorBrowser.to.(anonymous function) [as wait] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\browser.js:67:16)
    at UserContext.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\login\login.js:11:13)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
    at new ManagedPromise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
    at ControlFlow.promise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
    at schedulerExecute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
From: Task: Run it("Login: Try login without any credentials.") in control flow
    at UserContext.<anonymous> (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:19)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at runNext (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4264:13
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4172:9
    at handleError (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4244:11)
    at process.onerror (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:2371:17)
    at process.emit (events.js:198:13)
    at process.emit (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\source-map-support\source-map-support.js:439:21)
From asynchronous test: 
Error
    at Suite.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\login\login.js:9:3)
    at addSpecsToSuite (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
    at Env.describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
    at describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
    at Object.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\login\login.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)]]>
   </failure>
  </testcase>
  <testcase classname="Hybrent Login Module" name="Login: Try login with wrong credentials." time="8.337" />
  <testcase classname="Hybrent Login Module" name="Login: Try login with correct credentials." time="8.692" />
 </testsuite>
 <testsuite name="Dashboard test cases" timestamp="2019-10-25T19:20:27" hostname="localhost" time="29.067" errors="0" tests="11" skipped="0" disabled="0" failures="3">
  <testcase classname="Dashboard test cases" name="Verify that System gets redirected to Profile page when user clicks on Profile link" time="4.784" />
  <testcase classname="Dashboard test cases" name="Verify that system gets redirected to NOTIFICATION SETTINGS page when user clicks on Notification settings button" time="2.397" />
  <testcase classname="Dashboard test cases" name="Verify that System gets redirected to Alerts page when user clicks on Alerts link" time="2.497" />
  <testcase classname="Dashboard test cases" name="Verify that System gets redirected to &quot;Survey&quot; page when user clicks on &quot;Survey&quot; link." time="1.153" />
  <testcase classname="Dashboard test cases" name="Verify that System gets redirected to &quot;Change Password&quot; page when user clicks on &quot; Change Password&quot; link" time="3.151" />
  <testcase classname="Dashboard test cases" name="Verify that Notification icon  appears on top of page." time="0.525" />
  <testcase classname="Dashboard test cases" name="Verify that Notification icon  appears on top of page." time="0.075" />
  <testcase classname="Dashboard test cases" name="Verify that user gets redirected to “My Notifications” page, on clicking “View All” button" time="2.808" />
  <testcase classname="Dashboard test cases" name="Verify that user gets redirected to corresponding Report on clicking View More Reports button" time="1.037">
   <failure type="exception" message="Failed: No element found using locator: by.buttonText(&quot;View More Reports&quot;)"><![CDATA[NoSuchElementError: No element found using locator: by.buttonText("View More Reports")
    at elementArrayFinder.getWebElements.then (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:814:27)
    at ManagedPromise.invokeCallback_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
    at process._tickCallback (internal/process/next_tick.js:68:7)Error
    at ElementArrayFinder.applyAction_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:459:27)
    at ElementArrayFinder.(anonymous function).args [as click] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:91:29)
    at ElementFinder.(anonymous function).args [as click] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:831:22)
    at UserContext.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Dashboard\dashboard.js:108:20)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
    at new ManagedPromise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
    at ControlFlow.promise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
    at schedulerExecute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
From: Task: Run it("Verify that user gets redirected to corresponding Report on clicking View More Reports button") in control flow
    at UserContext.<anonymous> (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:19)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at QueueRunner.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4199:10)
    at Spec.queueRunnerFactory (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:909:35)
    at Spec.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:526:10)
    at UserContext.fn (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:5340:37)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at runNext (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)
From asynchronous test: 
Error
    at Suite.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Dashboard\dashboard.js:103:3)
    at addSpecsToSuite (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
    at Env.describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
    at describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
    at Object.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Dashboard\dashboard.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)]]>
   </failure>
  </testcase>
  <testcase classname="Dashboard test cases" name="Verify that relevant data appears under Monthly Purchase Order Value, Number of Backorders and Vendor Performance sections" time="6.012">
   <failure type="toContain" message="Expected &apos;2&apos; to contain &apos;Showing 1 to 2 of 2 entries&apos;."><![CDATA[Error: Failed expectation
    at F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Dashboard\dashboard.js:145:28
    at elementArrayFinder_.then (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:804:32)
    at ManagedPromise.invokeCallback_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
    at process._tickCallback (internal/process/next_tick.js:68:7)]]>
   </failure>
  </testcase>
  <testcase classname="Dashboard test cases" name="Verify that “Recent Orders” and “News &amp; Events” sections appear on Page." time="4.625">
   <failure type="exception" message="Failed: Index out of bound. Trying to access element at index: 0, but there are only 0 elements that match locator by.repeater(&quot;recentNewsDetails in dashboardData.recentNews&quot;)"><![CDATA[NoSuchElementError: Index out of bound. Trying to access element at index: 0, but there are only 0 elements that match locator by.repeater("recentNewsDetails in dashboardData.recentNews")
    at selenium_webdriver_1.promise.all.then (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:274:27)
    at ManagedPromise.invokeCallback_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
    at process._tickCallback (internal/process/next_tick.js:68:7)Error
    at ElementArrayFinder.applyAction_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:459:27)
    at ElementArrayFinder.(anonymous function).args [as click] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:91:29)
    at ElementFinder.(anonymous function).args [as click] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:831:22)
    at F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Dashboard\dashboard.js:186:47
    at ManagedPromise.invokeCallback_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: Run it("Verify that “Recent Orders” and “News & Events” sections appear on Page.") in control flow
    at UserContext.<anonymous> (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:19)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at QueueRunner.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4199:10)
    at Spec.queueRunnerFactory (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:909:35)
    at Spec.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:526:10)
    at UserContext.fn (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:5340:37)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at runNext (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)
From asynchronous test: 
Error
    at Suite.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Dashboard\dashboard.js:157:3)
    at addSpecsToSuite (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
    at Env.describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
    at describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
    at Object.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Dashboard\dashboard.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)]]>
   </failure>
  </testcase>
 </testsuite>
 <testsuite name="user default facility" timestamp="2019-10-25T19:20:56" hostname="localhost" time="1.388" errors="0" tests="1" skipped="0" disabled="0" failures="0">
  <testcase classname="user default facility" name="user default facility is" time="1.388" />
 </testsuite>
 <testsuite name="Hybrent Item Catalog Module" timestamp="2019-10-25T19:20:57" hostname="localhost" time="85.022" errors="0" tests="12" skipped="0" disabled="0" failures="2">
  <testcase classname="Hybrent Item Catalog Module" name="Item Catalog page should open" time="1.78" />
  <testcase classname="Hybrent Item Catalog Module" name="List page should display list of items and IC filters" time="0.251" />
  <testcase classname="Hybrent Item Catalog Module" name="verify that all the status option appear under the status dropdown" time="0.14" />
  <testcase classname="Hybrent Item Catalog Module" name="verify that Both, Inventory Item, Non-inventoryitem option appear under the type dropdown" time="0.106" />
  <testcase classname="Hybrent Item Catalog Module" name="verify all category option appear under the category dropdown" time="0.182">
   <failure type="toContain" message="Expected [ &apos;All Categories&apos;, &apos;Amenity&apos;, &apos;Crona11&apos;, &apos;hybrent technology&apos;, &apos;Raj1&apos;, &apos;Service&apos;, &apos;Tester&apos; ] to contain [ &apos;All Categories&apos;, &apos;Amenity&apos;, &apos;Crona1&apos;, &apos;hybrent technology&apos;, &apos;Service&apos;, &apos;Tester&apos; ]."><![CDATA[Error: Failed expectation
    at F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\ItemCatalog\Itemsection.js:76:24
    at ManagedPromise.invokeCallback_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
    at process._tickCallback (internal/process/next_tick.js:68:7)]]>
   </failure>
  </testcase>
  <testcase classname="Hybrent Item Catalog Module" name="verify all ordering_type option appear under the ordering_type dropdown" time="0.626">
   <failure type="toContain" message="Expected [ &apos;All&apos;, &apos;Amenity&apos;, &apos;General&apos;, &apos;Service&apos;, &apos;Free-Hand&apos;, &apos;Bill-Only&apos;, &apos;DME&apos; ] to contain [ &apos;All&apos;, &apos;Amenity&apos;, &apos;General&apos;, &apos;Service&apos;, &apos;Free-Hand&apos;, &apos;Bill-Only&apos;, &apos;DME&apos; ]."><![CDATA[Error: Failed expectation
    at F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\ItemCatalog\Itemsection.js:86:24
    at ManagedPromise.invokeCallback_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
    at process._tickCallback (internal/process/next_tick.js:68:7)]]>
   </failure>
  </testcase>
  <testcase classname="Hybrent Item Catalog Module" name="verify all consumption_type option appear under the consumption_type dropdown" time="0.586" />
  <testcase classname="Hybrent Item Catalog Module" name="Add Dme Item" time="23.496" />
  <testcase classname="Hybrent Item Catalog Module" name="Add General Item" time="18.041" />
  <testcase classname="Hybrent Item Catalog Module" name="Verify that &quot;Map Facility for item Sku --- pop up appears on the screen." time="12.13" />
  <testcase classname="Hybrent Item Catalog Module" name="Add Bill only Item" time="22.536" />
  <testcase classname="Hybrent Item Catalog Module" name="Add Amenity item" time="5.146" />
 </testsuite>
 <testsuite name="Hybrent Shop Module" timestamp="2019-10-25T19:22:22" hostname="localhost" time="8.792" errors="0" tests="5" skipped="0" disabled="0" failures="0">
  <testcase classname="Hybrent Shop Module" name="Verify that user default facility appear selected in shop page" time="2.418" />
  <testcase classname="Hybrent Shop Module" name="Verify that only General ACTIVE items are appearing on page and add them to cart" time="3.776" />
  <testcase classname="Hybrent Shop Module" name="Shop: Shows recently ordered items appear on page on selecting Recently ordered radio button" time="1.192" />
  <testcase classname="Hybrent Shop Module" name="Shop: Shows Most ordered items with Po count column sort descending if default layout is selected." time="0.773" />
  <testcase classname="Hybrent Shop Module" name="Shop: Shows all items that are marked as Favorite." time="0.633" />
 </testsuite>
 <testsuite name="Hybrent Cart Module" timestamp="2019-10-25T19:22:31" hostname="localhost" time="21.3" errors="0" tests="3" skipped="0" disabled="0" failures="0">
  <testcase classname="Hybrent Cart Module" name="Open cart page" time="1.685" />
  <testcase classname="Hybrent Cart Module" name="add item to cart" time="7.576" />
  <testcase classname="Hybrent Cart Module" name="Generate PO" time="12.039" />
 </testsuite>
 <testsuite name="Hybrent Order Module" timestamp="2019-10-25T19:22:52" hostname="localhost" time="27.574" errors="0" tests="5" skipped="0" disabled="0" failures="1">
  <testcase classname="Hybrent Order Module" name="Open order module" time="0.325" />
  <testcase classname="Hybrent Order Module" name="List page should display list of filters" time="2.814">
   <failure type="toBeTruthy" message="Expected false to be truthy."><![CDATA[Error: Failed expectation
    at UserContext.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Order\order.js:16:68)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
    at new ManagedPromise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
    at ControlFlow.promise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
    at schedulerExecute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2974:25)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7]]>
   </failure>
  </testcase>
  <testcase classname="Hybrent Order Module" name="Order list page search with PO# Found" time="7.388" />
  <testcase classname="Hybrent Order Module" name="verify that all option appears in Order drop down" time="2.121" />
  <testcase classname="Hybrent Order Module" name="add invoice for newly created order" time="14.925" />
 </testsuite>
 <testsuite name="Hybrent Receive Module" timestamp="2019-10-25T19:23:20" hostname="localhost" time="8.393" errors="0" tests="4" skipped="0" disabled="0" failures="1">
  <testcase classname="Hybrent Receive Module" name="Navigate to Receive module" time="1.316" />
  <testcase classname="Hybrent Receive Module" name="verify that all search filter appear on listing page" time="0.284">
   <failure type="toBeTruthy" message="Expected false to be truthy."><![CDATA[Error: Failed expectation
    at UserContext.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Receive\receivelist.js:19:68)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
    at new ManagedPromise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
    at ControlFlow.promise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
    at schedulerExecute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2974:25)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7]]>
   </failure>
  </testcase>
  <testcase classname="Hybrent Receive Module" name="verify that po search functionality is working fine" time="4.011" />
  <testcase classname="Hybrent Receive Module" name="verify that all option appears in order drop down on listing page" time="2.782" />
 </testsuite>
 <testsuite name="Hybrent Receive order" timestamp="2019-10-25T19:23:28" hostname="localhost" time="24.107" errors="0" tests="3" skipped="0" disabled="0" failures="2">
  <testcase classname="Hybrent Receive order" name="Open order detail page" time="3.71" />
  <testcase classname="Hybrent Receive order" name="verify that all option appear in order drop down" time="2.746" />
  <testcase classname="Hybrent Receive order" name="open order detail page to receive corresponding order" time="17.65">
   <failure type="toEqual" message="Expected &apos;New update available on this page, hit refresh to update Refresh&apos; to equal &apos;Order completed successfully.&apos;."><![CDATA[Error: Failed expectation
    at F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Receive\Receiveorder.js:55:49
    at arr.map (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:628:33)
    at Array.map (<anonymous>)
    at asElementFinders_.then (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:627:28)
    at ManagedPromise.invokeCallback_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7]]>
   </failure>
   <failure type="exception" message="Failed: No element found using locator: by.buttonText(&quot;Search&quot;)"><![CDATA[NoSuchElementError: No element found using locator: by.buttonText("Search")
    at elementArrayFinder.getWebElements.then (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:814:27)
    at ManagedPromise.invokeCallback_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
    at process._tickCallback (internal/process/next_tick.js:68:7)Error
    at ElementArrayFinder.applyAction_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:459:27)
    at ElementArrayFinder.(anonymous function).args [as click] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:91:29)
    at ElementFinder.(anonymous function).args [as click] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:831:22)
    at F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Receive\Receiveorder.js:58:42
    at arr.map (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:628:33)
    at Array.map (<anonymous>)
    at asElementFinders_.then (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:627:28)
    at ManagedPromise.invokeCallback_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
From: Task: Run it("open order detail page to receive corresponding order") in control flow
    at UserContext.<anonymous> (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:19)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at QueueRunner.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4199:10)
    at Spec.queueRunnerFactory (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:909:35)
    at Spec.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:526:10)
    at UserContext.fn (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:5340:37)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at runNext (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)
From asynchronous test: 
Error
    at Suite.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Receive\Receiveorder.js:26:3)
    at addSpecsToSuite (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
    at Env.describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
    at describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
    at Object.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Receive\Receiveorder.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)]]>
   </failure>
  </testcase>
 </testsuite>
 <testsuite name="Hybrent Templates Module" timestamp="2019-10-25T19:23:52" hostname="localhost" time="18.622" errors="0" tests="5" skipped="0" disabled="0" failures="2">
  <testcase classname="Hybrent Templates Module" name="Templates List page should open" time="2.14" />
  <testcase classname="Hybrent Templates Module" name="List page should display templates search filter" time="0.097" />
  <testcase classname="Hybrent Templates Module" name="Add Template" time="2.609" />
  <testcase classname="Hybrent Templates Module" name="Add item to newly created template" time="5.542" />
  <testcase classname="Hybrent Templates Module" name="Search template by name" time="8.233">
   <failure type="toContain" message="Expected &apos;&apos; to contain &apos;template1572011397898&apos;."><![CDATA[Error: Failed expectation
    at F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Template\Templatelist.js:47:22
    at elementArrayFinder_.then (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:804:32)
    at ManagedPromise.invokeCallback_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
    at process._tickCallback (internal/process/next_tick.js:68:7)]]>
   </failure>
   <failure type="toContain" message="Expected &apos;&apos; to contain &apos;template1572011397898&apos;."><![CDATA[Error: Failed expectation
    at F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Template\Templatelist.js:47:22
    at elementArrayFinder_.then (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:804:32)
    at ManagedPromise.invokeCallback_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
    at process._tickCallback (internal/process/next_tick.js:68:7)]]>
   </failure>
  </testcase>
 </testsuite>
 <testsuite name="Hybrent Scan IN Module" timestamp="2019-10-25T19:24:11" hostname="localhost" time="68.139" errors="0" tests="8" skipped="0" disabled="0" failures="0">
  <testcase classname="Hybrent Scan IN Module" name="Open scan in module" time="8.223" />
  <testcase classname="Hybrent Scan IN Module" name="List page should display Scan In filters and refresh button" time="0.138" />
  <testcase classname="Hybrent Scan IN Module" name="Scan In - Search items by item Name, sku, mfr" time="6.353" />
  <testcase classname="Hybrent Scan IN Module" name="Scan In - Add items for scan In by click on scan In button" time="12.008" />
  <testcase classname="Hybrent Scan IN Module" name="Scan In - Add DME items for scan In by click on scan In button" time="12.048" />
  <testcase classname="Hybrent Scan IN Module" name="Scan In - Search added items by item Name, sku, mfr" time="4.352" />
  <testcase classname="Hybrent Scan IN Module" name="add stock status for vendor stock item" time="15.643" />
  <testcase classname="Hybrent Scan IN Module" name="Scan In items - Complete scan In and item should display on inventory transaction page" time="9.373" />
 </testsuite>
 <testsuite name="Hybrent Bill &amp; Replace Module" timestamp="2019-10-25T19:25:19" hostname="localhost" time="24.567" errors="0" tests="4" skipped="0" disabled="0" failures="0">
  <testcase classname="Hybrent Bill &amp; Replace Module" name="Open Bill and Replace module" time="2.279" />
  <testcase classname="Hybrent Bill &amp; Replace Module" name="Verify that add item search filter appear on top of the page" time="0.069" />
  <testcase classname="Hybrent Bill &amp; Replace Module" name="Search item by SKU, MFR and Name " time="6.837" />
  <testcase classname="Hybrent Bill &amp; Replace Module" name="add item for Bill and replace by searching serial number" time="15.38" />
 </testsuite>
 <testsuite name="Hybrent ReplenishBin Module" timestamp="2019-10-25T19:25:44" hostname="localhost" time="14.004" errors="0" tests="3" skipped="0" disabled="0" failures="1">
  <testcase classname="Hybrent ReplenishBin Module" name="Open ReplenishBin module" time="2.38" />
  <testcase classname="Hybrent ReplenishBin Module" name="Verify that drop down and search filter appear on the page" time="0.542" />
  <testcase classname="Hybrent ReplenishBin Module" name="Add item to ReplenishBin cart by search filter" time="11.08">
   <failure type="exception" message="Failed: element not interactable
  (Session info: chrome=78.0.3904.70)
Build info: version: &apos;3.141.59&apos;, revision: &apos;e82be7d358&apos;, time: &apos;2018-11-14T08:25:53&apos;
System info: host: &apos;LAPTOP-QSN8IM2G&apos;, ip: &apos;10.0.0.136&apos;, os.name: &apos;Windows 10&apos;, os.arch: &apos;amd64&apos;, os.version: &apos;10.0&apos;, java.version: &apos;1.8.0_181&apos;
Driver info: driver.version: unknown"><![CDATA[WebDriverError: element not interactable
  (Session info: chrome=78.0.3904.70)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'LAPTOP-QSN8IM2G', ip: '10.0.0.136', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
Driver info: driver.version: unknown
    at Object.checkLegacyResponse (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: WebElement.click()
    at thenableWebDriverProxy.schedule (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:807:17)
    at WebElement.schedule_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:2010:25)
    at WebElement.click (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:2092:17)
    at actionFn (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:89:44)
    at Array.map (<anonymous>)
    at actionResults.getWebElements.then (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:461:65)
    at ManagedPromise.invokeCallback_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)Error
    at ElementArrayFinder.applyAction_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:459:27)
    at ElementArrayFinder.(anonymous function).args [as click] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:91:29)
    at ElementFinder.(anonymous function).args [as click] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:831:22)
    at UserContext.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Replenish_Bin\Replenish_bin.js:40:35)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
    at new ManagedPromise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
    at ControlFlow.promise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
    at schedulerExecute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
From: Task: Run it("Add item to ReplenishBin cart by search filter") in control flow
    at UserContext.<anonymous> (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:19)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at QueueRunner.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4199:10)
    at Spec.queueRunnerFactory (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:909:35)
    at Spec.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:526:10)
    at UserContext.fn (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:5340:37)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at runNext (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)
From asynchronous test: 
Error
    at Suite.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Replenish_Bin\Replenish_bin.js:25:3)
    at addSpecsToSuite (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
    at Env.describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
    at describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
    at Object.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Replenish_Bin\Replenish_bin.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)]]>
   </failure>
  </testcase>
 </testsuite>
 <testsuite name="Approve unapproved items" timestamp="2019-10-25T19:25:58" hostname="localhost" time="15.842" errors="0" tests="5" skipped="1" disabled="0" failures="0">
  <testcase classname="Approve unapproved items" name="approve items" time="3.022" />
  <testcase classname="Approve unapproved items" name="select user default facility" time="0.002">
   <skipped message="Temporarily disabled with xit" />
  </testcase>
  <testcase classname="Approve unapproved items" name="verify that search with status and vendor drop down field appear on page" time="0.364" />
  <testcase classname="Approve unapproved items" name="verify that user is able to search item with item name, alias, sku and vendor name" time="6.969" />
  <testcase classname="Approve unapproved items" name="Approve item after search" time="5.483" />
 </testsuite>
 <testsuite name="Hybrent Manage Inventory Module" timestamp="2019-10-25T19:26:13" hostname="localhost" time="23.711" errors="0" tests="8" skipped="0" disabled="0" failures="1">
  <testcase classname="Hybrent Manage Inventory Module" name="Manage Inventory page should open" time="4.38" />
  <testcase classname="Hybrent Manage Inventory Module" name="List page should display list of items and manage inventory filters" time="0.171" />
  <testcase classname="Hybrent Manage Inventory Module" name="Search items by Name" time="1.744" />
  <testcase classname="Hybrent Manage Inventory Module" name="Search items by alise" time="1.572" />
  <testcase classname="Hybrent Manage Inventory Module" name="Search items by sku" time="1.44" />
  <testcase classname="Hybrent Manage Inventory Module" name="Search items by mfr number" time="1.682">
   <failure type="exception" message="Failed: No element found using locator: by.binding(&quot;vendor.sku&quot;)"><![CDATA[NoSuchElementError: No element found using locator: by.binding("vendor.sku")
    at elementArrayFinder.getWebElements.then (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:814:27)
    at ManagedPromise.invokeCallback_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
    at process._tickCallback (internal/process/next_tick.js:68:7)Error
    at ElementArrayFinder.applyAction_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:459:27)
    at ElementArrayFinder.(anonymous function).args [as getText] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:91:29)
    at ElementFinder.(anonymous function).args [as getText] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:831:22)
    at F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Manage Inventory\manageinventory.js:63:50
    at arr.map (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:628:33)
    at Array.map (<anonymous>)
    at asElementFinders_.then (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:627:28)
    at ManagedPromise.invokeCallback_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
From: Task: Run it("Search items by mfr number") in control flow
    at UserContext.<anonymous> (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:19)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at QueueRunner.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4199:10)
    at Spec.queueRunnerFactory (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:909:35)
    at Spec.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:526:10)
    at UserContext.fn (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:5340:37)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at runNext (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)
From asynchronous test: 
Error
    at Suite.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Manage Inventory\manageinventory.js:59:3)
    at addSpecsToSuite (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
    at Env.describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
    at describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
    at Object.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Manage Inventory\manageinventory.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)]]>
   </failure>
  </testcase>
  <testcase classname="Hybrent Manage Inventory Module" name="Vendor filter should display items for selected vendor only." time="1.957" />
  <testcase classname="Hybrent Manage Inventory Module" name="Transfer Item" time="10.764" />
 </testsuite>
 <testsuite name="Inventory Transfer Module" timestamp="2019-10-25T19:26:37" hostname="localhost" time="5.597" errors="0" tests="4" skipped="1" disabled="0" failures="0">
  <testcase classname="Inventory Transfer Module" name="Open Inventory Transfer" time="2.079" />
  <testcase classname="Inventory Transfer Module" name="verify that user default facility appear selected on ITN listing page" time="0.002">
   <skipped message="Temporarily disabled with xit" />
  </testcase>
  <testcase classname="Inventory Transfer Module" name="List page should display all search and status filter" time="0.317" />
  <testcase classname="Inventory Transfer Module" name="search newly created ITN through manage inventory" time="3.199" />
 </testsuite>
 <testsuite name="Shipment Module" timestamp="2019-10-25T19:26:43" hostname="localhost" time="2.582" errors="0" tests="2" skipped="0" disabled="0" failures="0">
  <testcase classname="Shipment Module" name="Open Shipment module" time="2.25" />
  <testcase classname="Shipment Module" name="List page should display all search and status filter" time="0.332" />
 </testsuite>
 <testsuite name="physician module" timestamp="2019-10-25T19:26:45" hostname="localhost" time="8.232" errors="0" tests="3" skipped="0" disabled="0" failures="0">
  <testcase classname="physician module" name="Add a physician" time="6.897" />
  <testcase classname="physician module" name="verify that physican and facilities filter appear on page" time="0.076" />
  <testcase classname="physician module" name="verify that searching with Physician name, NPI and Facility wise working properly" time="1.259" />
 </testsuite>
 <testsuite name="operating room module" timestamp="2019-10-25T19:26:54" hostname="localhost" time="15.228" errors="0" tests="3" skipped="0" disabled="0" failures="0">
  <testcase classname="operating room module" name="Navigate to operating room" time="1.454" />
  <testcase classname="operating room module" name="List page should display list of items and IC filters" time="0.055" />
  <testcase classname="operating room module" name="add new operating room" time="13.717" />
 </testsuite>
 <testsuite name="Patient module" timestamp="2019-10-25T19:27:09" hostname="localhost" time="17.188" errors="0" tests="4" skipped="1" disabled="0" failures="0">
  <testcase classname="Patient module" name="Navigate to patient module" time="2.48" />
  <testcase classname="Patient module" name="Verify that search patient By filter appear on patient detail page" time="0.157" />
  <testcase classname="Patient module" name="verify that user is able to add patient by clicking on add patient button" time="14.55" />
  <testcase classname="Patient module" name="Patient: Update Patient." time="0.001">
   <skipped message="Temporarily disabled with xit" />
  </testcase>
 </testsuite>
 <testsuite name="Procedure module" timestamp="2019-10-25T19:27:26" hostname="localhost" time="18.854" errors="0" tests="5" skipped="0" disabled="0" failures="0">
  <testcase classname="Procedure module" name="verify that user get redirect to Procedure module on clicking procedure" time="1.95" />
  <testcase classname="Procedure module" name="verify that search filter appear on on procedure detail page" time="1.044" />
  <testcase classname="Procedure module" name="verify that on clicking add procedure button a new window to add procedure get opened" time="0.718" />
  <testcase classname="Procedure module" name="Create New Procedure after opening add procedure window" time="7.56" />
  <testcase classname="Procedure module" name="verify that user is able to Update created Procedure." time="7.582" />
 </testsuite>
 <testsuite name="Prefcard module" timestamp="2019-10-25T19:27:45" hostname="localhost" time="17.791" errors="0" tests="4" skipped="0" disabled="0" failures="0">
  <testcase classname="Prefcard module" name="verify that preference card module get opened on clicking prefcard" time="2.189" />
  <testcase classname="Prefcard module" name="verify that search filter and drop down options appear on pref card listing page" time="0.26" />
  <testcase classname="Prefcard module" name="verify that on clicking add Preference card button a new window to add procedure get opened" time="0.926" />
  <testcase classname="Prefcard module" name="verify that user is able to create new pref card from the add pref card window" time="14.414" />
 </testsuite>
 <testsuite name="Planner module" timestamp="2019-10-25T19:28:03" hostname="localhost" time="47.463" errors="0" tests="2" skipped="0" disabled="0" failures="1">
  <testcase classname="Planner module" name="Navigate to planner module" time="2.992" />
  <testcase classname="Planner module" name="Planner: add Cases." time="44.47">
   <failure type="exception" message="Failed: No element found using locator: by.cssContainingText(&quot;.fc-title&quot;, &quot;robert1572011397898&quot;)"><![CDATA[NoSuchElementError: No element found using locator: by.cssContainingText(".fc-title", "robert1572011397898")
    at elementArrayFinder.getWebElements.then (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:814:27)
    at ManagedPromise.invokeCallback_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
    at process._tickCallback (internal/process/next_tick.js:68:7)Error
    at ElementArrayFinder.applyAction_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:459:27)
    at ElementArrayFinder.(anonymous function).args [as click] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:91:29)
    at ElementFinder.(anonymous function).args [as click] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:831:22)
    at UserContext.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Planner\planner.js:69:83)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
    at new ManagedPromise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
    at ControlFlow.promise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
    at schedulerExecute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
From: Task: Run it("Planner: add Cases.") in control flow
    at UserContext.<anonymous> (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:19)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at QueueRunner.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4199:10)
    at Spec.queueRunnerFactory (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:909:35)
    at Spec.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:526:10)
    at UserContext.fn (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:5340:37)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at runNext (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)
From asynchronous test: 
Error
    at Suite.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Planner\planner.js:26:3)
    at addSpecsToSuite (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
    at Env.describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
    at describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
    at Object.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Planner\planner.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)]]>
   </failure>
  </testcase>
 </testsuite>
 <testsuite name="Picklist module" timestamp="2019-10-25T19:28:50" hostname="localhost" time="42.518" errors="0" tests="6" skipped="0" disabled="0" failures="0">
  <testcase classname="Picklist module" name="Navigate to picklist module" time="2.955" />
  <testcase classname="Picklist module" name="Verify that all search and drop down filter appear on the pick list page" time="0.189" />
  <testcase classname="Picklist module" name="Search newly created case" time="12.332" />
  <testcase classname="Picklist module" name="open and add normal notes in newly created case" time="8.154" />
  <testcase classname="Picklist module" name="increase item qty " time="8.483" />
  <testcase classname="Picklist module" name="move case to execute case" time="10.404" />
 </testsuite>
 <testsuite name="Execute Case module" timestamp="2019-10-25T19:29:33" hostname="localhost" time="39.58" errors="0" tests="4" skipped="0" disabled="0" failures="0">
  <testcase classname="Execute Case module" name="Navigate to Execute case module" time="2.868" />
  <testcase classname="Execute Case module" name="Verify that all search and drop down filter appear on the execute case page" time="0.197" />
  <testcase classname="Execute Case module" name="Search and open newly created case" time="13.75" />
  <testcase classname="Execute Case module" name="increase item hold qty and move case to complete case" time="22.764" />
 </testsuite>
 <testsuite name="All Cases module" timestamp="2019-10-25T19:30:12" hostname="localhost" time="19.849" errors="0" tests="3" skipped="0" disabled="0" failures="0">
  <testcase classname="All Cases module" name="Navigate to All cases module" time="2.407" />
  <testcase classname="All Cases module" name="Verify that all search and drop down filter appear on the All case page" time="0.237" />
  <testcase classname="All Cases module" name="Search and open newly created case" time="17.203" />
 </testsuite>
 <testsuite name="Hybrent Out Of stcok Module" timestamp="2019-10-25T19:30:32" hostname="localhost" time="3.562" errors="0" tests="1" skipped="0" disabled="0" failures="0">
  <testcase classname="Hybrent Out Of stcok Module" name="Out Of stock page should open" time="3.561" />
 </testsuite>
 <testsuite name="Approval flow" timestamp="2019-10-25T19:30:36" hostname="localhost" time="10.024" errors="0" tests="5" skipped="0" disabled="0" failures="0">
  <testcase classname="Approval flow" name="Open Approval flow module" time="1.45" />
  <testcase classname="Approval flow" name="verify that search filter with facility list and search button appear on the approval template page" time="0.291" />
  <testcase classname="Approval flow" name="add new approval flow template" time="4.908" />
  <testcase classname="Approval flow" name="search newly created approval flow" time="1.258" />
  <testcase classname="Approval flow" name="delete newly created approval flow" time="2.115" />
 </testsuite>
 <testsuite name="Account Receivable Code" timestamp="2019-10-25T19:30:46" hostname="localhost" time="14.006" errors="0" tests="5" skipped="0" disabled="0" failures="0">
  <testcase classname="Account Receivable Code" name="Open Account Receivable Code module" time="1.094" />
  <testcase classname="Account Receivable Code" name="verify that search filter with facility list and search button appear on the Account Receivable Code page" time="0.217" />
  <testcase classname="Account Receivable Code" name="add new Account Receivable Code" time="6.047" />
  <testcase classname="Account Receivable Code" name="search newly created Account Receivable Code by given name and code" time="4.568" />
  <testcase classname="Account Receivable Code" name="delete newly created Account Receivable Code" time="2.078" />
 </testsuite>
 <testsuite name="Contract Management" timestamp="2019-10-25T19:31:00" hostname="localhost" time="1.269" errors="0" tests="2" skipped="0" disabled="0" failures="0">
  <testcase classname="Contract Management" name="Open Contract Management module" time="1.097" />
  <testcase classname="Contract Management" name="verify that search and status filter appear on the page" time="0.171" />
 </testsuite>
 <testsuite name="Department" timestamp="2019-10-25T19:31:01" hostname="localhost" time="19.609" errors="0" tests="6" skipped="0" disabled="0" failures="0">
  <testcase classname="Department" name="Open Department module" time="1.126" />
  <testcase classname="Department" name="verify that search and facility fiter with search and add button appear on the page" time="0.316" />
  <testcase classname="Department" name="add new department" time="7.141" />
  <testcase classname="Department" name="search newly created department name by its name" time="2.934" />
  <testcase classname="Department" name="update the newly created department" time="2.561" />
  <testcase classname="Department" name="delete newly created department" time="5.529" />
 </testsuite>
 <testsuite name="Facilities" timestamp="2019-10-25T19:31:21" hostname="localhost" time="6.257" errors="0" tests="3" skipped="0" disabled="0" failures="0">
  <testcase classname="Facilities" name="Open facilities module" time="1.05" />
  <testcase classname="Facilities" name="verify that search filter appear on the facility listing page" time="0.16" />
  <testcase classname="Facilities" name="search facility by facility name" time="5.045" />
 </testsuite>
 <testsuite name="GL code moudle" timestamp="2019-10-25T19:31:27" hostname="localhost" time="6.038" errors="0" tests="4" skipped="0" disabled="0" failures="0">
  <testcase classname="GL code moudle" name="Open GL code module" time="1.033" />
  <testcase classname="GL code moudle" name="verify that search filter appear on the GL code page" time="0.201" />
  <testcase classname="GL code moudle" name="Add new Gl Code" time="2.865" />
  <testcase classname="GL code moudle" name="verify that user is able to search gl code by name" time="1.938" />
 </testsuite>
 <testsuite name="Identity Provider moudle" timestamp="2019-10-25T19:31:33" hostname="localhost" time="16.277" errors="0" tests="7" skipped="0" disabled="0" failures="1">
  <testcase classname="Identity Provider moudle" name="Open Identity Provider module" time="1.289" />
  <testcase classname="Identity Provider moudle" name="verify that search filter appear on the Identity Provider page" time="0.159" />
  <testcase classname="Identity Provider moudle" name="search Identity Provider by PO name" time="2.822" />
  <testcase classname="Identity Provider moudle" name="search Identity Provider by Inventory_Management name" time="3.13" />
  <testcase classname="Identity Provider moudle" name="search Identity Provider by Inventory Transfer name" time="2.963" />
  <testcase classname="Identity Provider moudle" name="verify that user get redirect to manage pattern on clicking correponding link appear in drop down" time="4.465" />
  <testcase classname="Identity Provider moudle" name="verify that user get redirect to Dashboard on clicking close button appear in drop down" time="1.448">
   <failure type="exception" message="Failed: element click intercepted: Element &lt;button class=&quot;btn btn-default dropdown-toggle no-margin&quot; type=&quot;button&quot; data-toggle=&quot;dropdown&quot;&gt;...&lt;/button&gt; is not clickable at point (1343, 117). Other element would receive the click: &lt;div class=&quot;col-sm-18 ng-scope&quot;&gt;...&lt;/div&gt;
  (Session info: chrome=78.0.3904.70)
Build info: version: &apos;3.141.59&apos;, revision: &apos;e82be7d358&apos;, time: &apos;2018-11-14T08:25:53&apos;
System info: host: &apos;LAPTOP-QSN8IM2G&apos;, ip: &apos;10.0.0.136&apos;, os.name: &apos;Windows 10&apos;, os.arch: &apos;amd64&apos;, os.version: &apos;10.0&apos;, java.version: &apos;1.8.0_181&apos;
Driver info: driver.version: unknown"><![CDATA[WebDriverError: element click intercepted: Element <button class="btn btn-default dropdown-toggle no-margin" type="button" data-toggle="dropdown">...</button> is not clickable at point (1343, 117). Other element would receive the click: <div class="col-sm-18 ng-scope">...</div>
  (Session info: chrome=78.0.3904.70)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'LAPTOP-QSN8IM2G', ip: '10.0.0.136', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
Driver info: driver.version: unknown
    at Object.checkLegacyResponse (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: WebElement.click()
    at thenableWebDriverProxy.schedule (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:807:17)
    at WebElement.schedule_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:2010:25)
    at WebElement.click (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:2092:17)
    at actionFn (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:89:44)
    at Array.map (<anonymous>)
    at actionResults.getWebElements.then (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:461:65)
    at ManagedPromise.invokeCallback_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)Error
    at ElementArrayFinder.applyAction_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:459:27)
    at ElementArrayFinder.(anonymous function).args [as click] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:91:29)
    at ElementFinder.(anonymous function).args [as click] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:831:22)
    at UserContext.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\Identity_Provider.js:63:87)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
    at new ManagedPromise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
    at ControlFlow.promise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
    at schedulerExecute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
From: Task: Run it("verify that user get redirect to Dashboard on clicking close button appear in drop down") in control flow
    at UserContext.<anonymous> (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:19)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at QueueRunner.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4199:10)
    at Spec.queueRunnerFactory (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:909:35)
    at Spec.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:526:10)
    at UserContext.fn (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:5340:37)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at runNext (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)
From asynchronous test: 
Error
    at Suite.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\Identity_Provider.js:58:3)
    at addSpecsToSuite (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
    at Env.describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
    at describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
    at Object.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\Identity_Provider.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)]]>
   </failure>
  </testcase>
 </testsuite>
 <testsuite name="Import Vendor Bill Only Items" timestamp="2019-10-25T19:31:49" hostname="localhost" time="1.901" errors="0" tests="2" skipped="0" disabled="0" failures="0">
  <testcase classname="Import Vendor Bill Only Items" name="Open Import Vendor Bill Only Items module" time="1.716" />
  <testcase classname="Import Vendor Bill Only Items" name="verify that search and status filter appear on the page" time="0.184" />
 </testsuite>
 <testsuite name="Inventory Transactions" timestamp="2019-10-25T19:31:51" hostname="localhost" time="13.686" errors="0" tests="5" skipped="0" disabled="0" failures="0">
  <testcase classname="Inventory Transactions" name="Open Inventory Transactions module" time="1.594" />
  <testcase classname="Inventory Transactions" name="verify that search and status filter appear on the page" time="0.255" />
  <testcase classname="Inventory Transactions" name="search item by description" time="4.094" />
  <testcase classname="Inventory Transactions" name="search item by alias" time="3.926" />
  <testcase classname="Inventory Transactions" name="search item by sku" time="3.816" />
 </testsuite>
 <testsuite name="Invoice Payment Terms" timestamp="2019-10-25T19:32:05" hostname="localhost" time="10.642" errors="0" tests="6" skipped="0" disabled="0" failures="0">
  <testcase classname="Invoice Payment Terms" name="Open Invoice Payment Terms module" time="0.913" />
  <testcase classname="Invoice Payment Terms" name="verify that search and facility fiter with search and add button appear on the page" time="0.18" />
  <testcase classname="Invoice Payment Terms" name="add new payment term" time="2.913" />
  <testcase classname="Invoice Payment Terms" name="search newly created payment term by name" time="0.618" />
  <testcase classname="Invoice Payment Terms" name="update the newly special instruction" time="3.468" />
  <testcase classname="Invoice Payment Terms" name="delete newly created special instruction" time="2.55" />
 </testsuite>
 <testsuite name="Item Categories" timestamp="2019-10-25T19:32:15" hostname="localhost" time="28.076" errors="0" tests="7" skipped="0" disabled="0" failures="1">
  <testcase classname="Item Categories" name="Open Item Categories module" time="0.964" />
  <testcase classname="Item Categories" name="verify that search and status filter appear on the page" time="0.112" />
  <testcase classname="Item Categories" name="add new Category" time="4.151" />
  <testcase classname="Item Categories" name="search newly created category" time="2.83">
   <failure type="exception" message="Failed: text is not defined"><![CDATA[ReferenceError: text is not defined
    at F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\Item_Categories.js:36:14
    at elementArrayFinder_.then (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:804:32)
    at ManagedPromise.invokeCallback_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: Run it("search newly created category") in control flow
    at UserContext.<anonymous> (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:19)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at QueueRunner.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4199:10)
    at Spec.queueRunnerFactory (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:909:35)
    at Spec.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:526:10)
    at UserContext.fn (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:5340:37)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at runNext (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)
From asynchronous test: 
Error
    at Suite.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\Item_Categories.js:31:3)
    at addSpecsToSuite (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
    at Env.describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
    at describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
    at Object.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\Item_Categories.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)]]>
   </failure>
  </testcase>
  <testcase classname="Item Categories" name="update newly created category" time="6.779" />
  <testcase classname="Item Categories" name="verify that on clicking category name user get redirect to item master page" time="6.158" />
  <testcase classname="Item Categories" name="delete newly create category" time="7.082" />
 </testsuite>
 <testsuite name="Items Change Log" timestamp="2019-10-25T19:32:43" hostname="localhost" time="14.138" errors="0" tests="5" skipped="0" disabled="0" failures="3">
  <testcase classname="Items Change Log" name="Open Items Change Log module" time="1.077" />
  <testcase classname="Items Change Log" name="verify that search and status filter appear on the page" time="0.168" />
  <testcase classname="Items Change Log" name="search item by description" time="4.202">
   <failure type="exception" message="Failed: No element found using locator: by.repeater(&quot;itemLog in itemChangeLogData.rows&quot;)"><![CDATA[NoSuchElementError: No element found using locator: by.repeater("itemLog in itemChangeLogData.rows")
    at elementArrayFinder.getWebElements.then (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:814:27)
    at ManagedPromise.invokeCallback_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
    at process._tickCallback (internal/process/next_tick.js:68:7)Error
    at ElementArrayFinder.applyAction_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:459:27)
    at ElementArrayFinder.(anonymous function).args [as getText] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:91:29)
    at ElementFinder.(anonymous function).args [as getText] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:831:22)
    at UserContext.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\Item_change_log.js:28:63)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
    at new ManagedPromise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
    at ControlFlow.promise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
    at schedulerExecute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
From: Task: Run it("search item by description") in control flow
    at UserContext.<anonymous> (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:19)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at QueueRunner.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4199:10)
    at Spec.queueRunnerFactory (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:909:35)
    at Spec.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:526:10)
    at UserContext.fn (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:5340:37)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at runNext (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)
From asynchronous test: 
Error
    at Suite.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\Item_change_log.js:23:3)
    at addSpecsToSuite (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
    at Env.describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
    at describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
    at Object.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\Item_change_log.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)]]>
   </failure>
  </testcase>
  <testcase classname="Items Change Log" name="search item by alias" time="4.395">
   <failure type="exception" message="Failed: No element found using locator: by.repeater(&quot;itemLog in itemChangeLogData.rows&quot;)"><![CDATA[NoSuchElementError: No element found using locator: by.repeater("itemLog in itemChangeLogData.rows")
    at elementArrayFinder.getWebElements.then (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:814:27)
    at ManagedPromise.invokeCallback_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
    at process._tickCallback (internal/process/next_tick.js:68:7)Error
    at ElementArrayFinder.applyAction_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:459:27)
    at ElementArrayFinder.(anonymous function).args [as getText] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:91:29)
    at ElementFinder.(anonymous function).args [as getText] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:831:22)
    at UserContext.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\Item_change_log.js:37:63)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
    at new ManagedPromise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
    at ControlFlow.promise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
    at schedulerExecute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
From: Task: Run it("search item by alias") in control flow
    at UserContext.<anonymous> (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:19)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at QueueRunner.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4199:10)
    at Spec.queueRunnerFactory (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:909:35)
    at Spec.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:526:10)
    at UserContext.fn (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:5340:37)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at runNext (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)
From asynchronous test: 
Error
    at Suite.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\Item_change_log.js:32:3)
    at addSpecsToSuite (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
    at Env.describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
    at describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
    at Object.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\Item_change_log.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)]]>
   </failure>
  </testcase>
  <testcase classname="Items Change Log" name="search item by sku" time="4.293">
   <failure type="exception" message="Failed: No element found using locator: by.repeater(&quot;itemLog in itemChangeLogData.rows&quot;)"><![CDATA[NoSuchElementError: No element found using locator: by.repeater("itemLog in itemChangeLogData.rows")
    at elementArrayFinder.getWebElements.then (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:814:27)
    at ManagedPromise.invokeCallback_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
    at process._tickCallback (internal/process/next_tick.js:68:7)Error
    at ElementArrayFinder.applyAction_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:459:27)
    at ElementArrayFinder.(anonymous function).args [as getText] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:91:29)
    at ElementFinder.(anonymous function).args [as getText] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:831:22)
    at UserContext.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\Item_change_log.js:47:63)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
    at new ManagedPromise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
    at ControlFlow.promise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
    at schedulerExecute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
From: Task: Run it("search item by sku") in control flow
    at UserContext.<anonymous> (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:19)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at QueueRunner.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4199:10)
    at Spec.queueRunnerFactory (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:909:35)
    at Spec.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:526:10)
    at UserContext.fn (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:5340:37)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at runNext (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)
From asynchronous test: 
Error
    at Suite.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\Item_change_log.js:42:3)
    at addSpecsToSuite (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
    at Env.describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
    at describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
    at Object.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\Item_change_log.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)]]>
   </failure>
  </testcase>
 </testsuite>
 <testsuite name="Link item" timestamp="2019-10-25T19:32:58" hostname="localhost" time="20.627" errors="0" tests="8" skipped="0" disabled="0" failures="6">
  <testcase classname="Link item" name="Open link item module" time="1.349" />
  <testcase classname="Link item" name="verify that search and status filter appear on the page" time="0.191" />
  <testcase classname="Link item" name="verify that user is able to create new link item" time="0.02">
   <failure type="exception" message="Failed: element(...).clear(...).sendkeys is not a function"><![CDATA[TypeError: element(...).clear(...).sendkeys is not a function
    at UserContext.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\Linkitem.js:24:55)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
    at new ManagedPromise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
    at ControlFlow.promise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
    at schedulerExecute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2974:25)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: Run it("verify that user is able to create new link item") in control flow
    at UserContext.<anonymous> (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:19)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at QueueRunner.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4199:10)
    at Spec.queueRunnerFactory (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:909:35)
    at Spec.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:526:10)
    at UserContext.fn (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:5340:37)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at runNext (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)
From asynchronous test: 
Error
    at Suite.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\Linkitem.js:21:3)
    at addSpecsToSuite (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
    at Env.describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
    at describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
    at Object.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\Linkitem.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)]]>
   </failure>
  </testcase>
  <testcase classname="Link item" name="search newly created link item by description" time="4.123">
   <failure type="exception" message="Failed: No element found using locator: by.repeater(&quot;item in linkItems&quot;)"><![CDATA[NoSuchElementError: No element found using locator: by.repeater("item in linkItems")
    at elementArrayFinder.getWebElements.then (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:814:27)
    at ManagedPromise.invokeCallback_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
    at process._tickCallback (internal/process/next_tick.js:68:7)Error
    at ElementArrayFinder.applyAction_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:459:27)
    at ElementArrayFinder.(anonymous function).args [as getText] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:91:29)
    at ElementFinder.(anonymous function).args [as getText] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:831:22)
    at UserContext.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\Linkitem.js:44:47)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
    at new ManagedPromise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
    at ControlFlow.promise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
    at schedulerExecute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
From: Task: Run it("search newly created link item by description") in control flow
    at UserContext.<anonymous> (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:19)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at QueueRunner.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4199:10)
    at Spec.queueRunnerFactory (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:909:35)
    at Spec.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:526:10)
    at UserContext.fn (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:5340:37)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at runNext (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)
From asynchronous test: 
Error
    at Suite.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\Linkitem.js:39:3)
    at addSpecsToSuite (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
    at Env.describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
    at describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
    at Object.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\Linkitem.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)]]>
   </failure>
  </testcase>
  <testcase classname="Link item" name="search newly created link item by linkitem key" time="4.248">
   <failure type="exception" message="Failed: No element found using locator: by.repeater(&quot;item in linkItems&quot;)"><![CDATA[NoSuchElementError: No element found using locator: by.repeater("item in linkItems")
    at elementArrayFinder.getWebElements.then (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:814:27)
    at ManagedPromise.invokeCallback_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
    at process._tickCallback (internal/process/next_tick.js:68:7)Error
    at ElementArrayFinder.applyAction_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:459:27)
    at ElementArrayFinder.(anonymous function).args [as getText] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:91:29)
    at ElementFinder.(anonymous function).args [as getText] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:831:22)
    at UserContext.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\Linkitem.js:53:47)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
    at new ManagedPromise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
    at ControlFlow.promise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
    at schedulerExecute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
From: Task: Run it("search newly created link item by linkitem key") in control flow
    at UserContext.<anonymous> (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:19)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at QueueRunner.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4199:10)
    at Spec.queueRunnerFactory (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:909:35)
    at Spec.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:526:10)
    at UserContext.fn (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:5340:37)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at runNext (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)
From asynchronous test: 
Error
    at Suite.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\Linkitem.js:48:3)
    at addSpecsToSuite (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
    at Env.describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
    at describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
    at Object.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\Linkitem.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)]]>
   </failure>
  </testcase>
  <testcase classname="Link item" name="search newly created link item by alias" time="4.299">
   <failure type="exception" message="Failed: No element found using locator: by.repeater(&quot;item in linkItems&quot;)"><![CDATA[NoSuchElementError: No element found using locator: by.repeater("item in linkItems")
    at elementArrayFinder.getWebElements.then (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:814:27)
    at ManagedPromise.invokeCallback_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
    at process._tickCallback (internal/process/next_tick.js:68:7)Error
    at ElementArrayFinder.applyAction_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:459:27)
    at ElementArrayFinder.(anonymous function).args [as getText] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:91:29)
    at ElementFinder.(anonymous function).args [as getText] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:831:22)
    at UserContext.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\Linkitem.js:63:47)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
    at new ManagedPromise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
    at ControlFlow.promise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
    at schedulerExecute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
From: Task: Run it("search newly created link item by alias") in control flow
    at UserContext.<anonymous> (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:19)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at QueueRunner.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4199:10)
    at Spec.queueRunnerFactory (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:909:35)
    at Spec.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:526:10)
    at UserContext.fn (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:5340:37)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at runNext (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)
From asynchronous test: 
Error
    at Suite.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\Linkitem.js:58:3)
    at addSpecsToSuite (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
    at Env.describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
    at describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
    at Object.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\Linkitem.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)]]>
   </failure>
  </testcase>
  <testcase classname="Link item" name="update link item" time="3.14">
   <failure type="exception" message="Failed: No element found using locator: By(xpath, i.fa-edit)"><![CDATA[NoSuchElementError: No element found using locator: By(xpath, i.fa-edit)
    at elementArrayFinder.getWebElements.then (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:814:27)
    at ManagedPromise.invokeCallback_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
    at process._tickCallback (internal/process/next_tick.js:68:7)Error
    at ElementArrayFinder.applyAction_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:459:27)
    at ElementArrayFinder.(anonymous function).args [as click] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:91:29)
    at ElementFinder.(anonymous function).args [as click] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:831:22)
    at UserContext.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\Linkitem.js:71:36)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
    at new ManagedPromise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
    at ControlFlow.promise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
    at schedulerExecute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
From: Task: Run it("update link item") in control flow
    at UserContext.<anonymous> (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:19)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at QueueRunner.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4199:10)
    at Spec.queueRunnerFactory (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:909:35)
    at Spec.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:526:10)
    at UserContext.fn (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:5340:37)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at runNext (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)
From asynchronous test: 
Error
    at Suite.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\Linkitem.js:68:3)
    at addSpecsToSuite (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
    at Env.describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
    at describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
    at Object.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\Linkitem.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)]]>
   </failure>
  </testcase>
  <testcase classname="Link item" name="delete link item" time="3.255">
   <failure type="exception" message="Failed: invalid selector: Unable to locate an element with the xpath expression i.glyphicon glyphicon-trash text-danger action-button because of the following error:
SyntaxError: Failed to execute &apos;evaluate&apos; on &apos;Document&apos;: The string &apos;i.glyphicon glyphicon-trash text-danger action-button&apos; is not a valid XPath expression.
  (Session info: chrome=78.0.3904.70)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/invalid_selector_exception.html
Build info: version: &apos;3.141.59&apos;, revision: &apos;e82be7d358&apos;, time: &apos;2018-11-14T08:25:53&apos;
System info: host: &apos;LAPTOP-QSN8IM2G&apos;, ip: &apos;10.0.0.136&apos;, os.name: &apos;Windows 10&apos;, os.arch: &apos;amd64&apos;, os.version: &apos;10.0&apos;, java.version: &apos;1.8.0_181&apos;
Driver info: driver.version: unknown"><![CDATA[InvalidSelectorError: invalid selector: Unable to locate an element with the xpath expression i.glyphicon glyphicon-trash text-danger action-button because of the following error:
SyntaxError: Failed to execute 'evaluate' on 'Document': The string 'i.glyphicon glyphicon-trash text-danger action-button' is not a valid XPath expression.
  (Session info: chrome=78.0.3904.70)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/invalid_selector_exception.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'LAPTOP-QSN8IM2G', ip: '10.0.0.136', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
Driver info: driver.version: unknown
    at Object.checkLegacyResponse (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: WebDriver.findElements(By(xpath, i.glyphicon glyphicon-trash text-danger action-button))
    at thenableWebDriverProxy.schedule (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:807:17)
    at thenableWebDriverProxy.findElements (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:1048:19)
    at ptor.waitForAngular.then (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:159:44)
    at ManagedPromise.invokeCallback_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
    at process._tickCallback (internal/process/next_tick.js:68:7)Error
    at ElementArrayFinder.applyAction_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:459:27)
    at ElementArrayFinder.(anonymous function).args [as click] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:91:29)
    at ElementFinder.(anonymous function).args [as click] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:831:22)
    at UserContext.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\Linkitem.js:80:80)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
    at new ManagedPromise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
    at ControlFlow.promise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
    at schedulerExecute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
From: Task: Run it("delete link item") in control flow
    at UserContext.<anonymous> (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:19)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at QueueRunner.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4199:10)
    at Spec.queueRunnerFactory (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:909:35)
    at Spec.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:526:10)
    at UserContext.fn (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:5340:37)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at runNext (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)
From asynchronous test: 
Error
    at Suite.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\Linkitem.js:77:3)
    at addSpecsToSuite (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
    at Env.describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
    at describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
    at Object.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\Linkitem.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)]]>
   </failure>
  </testcase>
 </testsuite>
 <testsuite name="Manage pattern" timestamp="2019-10-25T19:33:18" hostname="localhost" time="5.932" errors="0" tests="2" skipped="0" disabled="0" failures="0">
  <testcase classname="Manage pattern" name="Open manage pattern module" time="1.772" />
  <testcase classname="Manage pattern" name="Add new pattern" time="4.159" />
 </testsuite>
 <testsuite name="Manufacturer" timestamp="2019-10-25T19:33:24" hostname="localhost" time="1.238" errors="0" tests="2" skipped="0" disabled="0" failures="0">
  <testcase classname="Manufacturer" name="Open Manfacturer module" time="1.058" />
  <testcase classname="Manufacturer" name="verify that search filter and search button appear on the page" time="0.179" />
 </testsuite>
 <testsuite name="News moudle" timestamp="2019-10-25T19:33:25" hostname="localhost" time="5.102" errors="0" tests="6" skipped="0" disabled="0" failures="4">
  <testcase classname="News moudle" name="Open News module" time="1.092" />
  <testcase classname="News moudle" name="verify that search filter appear on the News detail page" time="0.25" />
  <testcase classname="News moudle" name="Add new News" time="1.821">
   <failure type="exception" message="Failed: No element found using locator: by.buttonText(&quot;Save&quot;)"><![CDATA[NoSuchElementError: No element found using locator: by.buttonText("Save")
    at elementArrayFinder.getWebElements.then (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:814:27)
    at ManagedPromise.invokeCallback_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
    at process._tickCallback (internal/process/next_tick.js:68:7)Error
    at ElementArrayFinder.applyAction_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:459:27)
    at ElementArrayFinder.(anonymous function).args [as click] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:91:29)
    at ElementFinder.(anonymous function).args [as click] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:831:22)
    at UserContext.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\News.js:26:36)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
    at new ManagedPromise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
    at ControlFlow.promise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
    at schedulerExecute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
From: Task: Run it("Add new News") in control flow
    at UserContext.<anonymous> (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:19)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at QueueRunner.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4199:10)
    at Spec.queueRunnerFactory (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:909:35)
    at Spec.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:526:10)
    at UserContext.fn (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:5340:37)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at runNext (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)
From asynchronous test: 
Error
    at Suite.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\News.js:22:3)
    at addSpecsToSuite (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
    at Env.describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
    at describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
    at Object.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\News.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)]]>
   </failure>
  </testcase>
  <testcase classname="News moudle" name="verify that user is able to search news by title" time="0.964">
   <failure type="exception" message="Failed: No element found using locator: by.model(&quot;searchFilter&quot;)"><![CDATA[NoSuchElementError: No element found using locator: by.model("searchFilter")
    at elementArrayFinder.getWebElements.then (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:814:27)
    at ManagedPromise.invokeCallback_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
    at process._tickCallback (internal/process/next_tick.js:68:7)Error
    at ElementArrayFinder.applyAction_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:459:27)
    at ElementArrayFinder.(anonymous function).args [as clear] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:91:29)
    at ElementFinder.(anonymous function).args [as clear] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:831:22)
    at UserContext.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\News.js:37:39)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
    at new ManagedPromise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
    at ControlFlow.promise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
    at schedulerExecute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)Error
    at ElementArrayFinder.applyAction_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:459:27)
    at ElementArrayFinder.(anonymous function).args [as sendKeys] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:91:29)
    at ElementFinder.(anonymous function).args [as sendKeys] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:831:22)
    at UserContext.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\News.js:37:47)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
    at new ManagedPromise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
    at ControlFlow.promise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
    at schedulerExecute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
From: Task: Run it("verify that user is able to search news by title") in control flow
    at UserContext.<anonymous> (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:19)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at QueueRunner.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4199:10)
    at Spec.queueRunnerFactory (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:909:35)
    at Spec.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:526:10)
    at UserContext.fn (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:5340:37)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at runNext (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)
From asynchronous test: 
Error
    at Suite.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\News.js:36:3)
    at addSpecsToSuite (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
    at Env.describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
    at describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
    at Object.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\News.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)]]>
   </failure>
  </testcase>
  <testcase classname="News moudle" name="verify that user is able to edit the newly created news" time="0.516">
   <failure type="exception" message="Failed: No element found using locator: by.model(&quot;searchFilter&quot;)"><![CDATA[NoSuchElementError: No element found using locator: by.model("searchFilter")
    at elementArrayFinder.getWebElements.then (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:814:27)
    at ManagedPromise.invokeCallback_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
    at process._tickCallback (internal/process/next_tick.js:68:7)Error
    at ElementArrayFinder.applyAction_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:459:27)
    at ElementArrayFinder.(anonymous function).args [as clear] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:91:29)
    at ElementFinder.(anonymous function).args [as clear] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:831:22)
    at UserContext.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\News.js:44:39)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
    at new ManagedPromise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
    at ControlFlow.promise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
    at schedulerExecute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)Error
    at ElementArrayFinder.applyAction_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:459:27)
    at ElementArrayFinder.(anonymous function).args [as sendKeys] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:91:29)
    at ElementFinder.(anonymous function).args [as sendKeys] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:831:22)
    at UserContext.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\News.js:44:47)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
    at new ManagedPromise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
    at ControlFlow.promise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
    at schedulerExecute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
From: Task: Run it("verify that user is able to edit the newly created news") in control flow
    at UserContext.<anonymous> (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:19)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at QueueRunner.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4199:10)
    at Spec.queueRunnerFactory (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:909:35)
    at Spec.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:526:10)
    at UserContext.fn (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:5340:37)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at runNext (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)
From asynchronous test: 
Error
    at Suite.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\News.js:43:3)
    at addSpecsToSuite (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
    at Env.describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
    at describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
    at Object.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\News.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)]]>
   </failure>
  </testcase>
  <testcase classname="News moudle" name="verify that user can delete newly created news" time="0.459">
   <failure type="exception" message="Failed: No element found using locator: by.model(&quot;searchFilter&quot;)"><![CDATA[NoSuchElementError: No element found using locator: by.model("searchFilter")
    at elementArrayFinder.getWebElements.then (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:814:27)
    at ManagedPromise.invokeCallback_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
    at process._tickCallback (internal/process/next_tick.js:68:7)Error
    at ElementArrayFinder.applyAction_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:459:27)
    at ElementArrayFinder.(anonymous function).args [as clear] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:91:29)
    at ElementFinder.(anonymous function).args [as clear] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:831:22)
    at UserContext.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\News.js:54:39)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
    at new ManagedPromise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
    at ControlFlow.promise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
    at schedulerExecute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)Error
    at ElementArrayFinder.applyAction_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:459:27)
    at ElementArrayFinder.(anonymous function).args [as sendKeys] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:91:29)
    at ElementFinder.(anonymous function).args [as sendKeys] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:831:22)
    at UserContext.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\News.js:54:47)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
    at new ManagedPromise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
    at ControlFlow.promise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
    at schedulerExecute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
From: Task: Run it("verify that user can delete newly created news") in control flow
    at UserContext.<anonymous> (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:19)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at QueueRunner.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4199:10)
    at Spec.queueRunnerFactory (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:909:35)
    at Spec.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:526:10)
    at UserContext.fn (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:5340:37)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at runNext (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)
From asynchronous test: 
Error
    at Suite.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\News.js:53:3)
    at addSpecsToSuite (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
    at Env.describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
    at describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
    at Object.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\News.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)]]>
   </failure>
  </testcase>
 </testsuite>
 <testsuite name="Payor Code" timestamp="2019-10-25T19:33:30" hostname="localhost" time="12.357" errors="0" tests="5" skipped="1" disabled="0" failures="0">
  <testcase classname="Payor Code" name="Open Payor Code module" time="1.926" />
  <testcase classname="Payor Code" name="verify that search filter with facility list and search button appear on the Payor Code page" time="0.161" />
  <testcase classname="Payor Code" name="add new Payor Code" time="5.523" />
  <testcase classname="Payor Code" name="search newly created Payor Code by given name and code" time="4.745" />
  <testcase classname="Payor Code" name="delete newly created Payor Code" time="0.001">
   <skipped message="Temporarily disabled with xit" />
  </testcase>
 </testsuite>
 <testsuite name="PO special instruction" timestamp="2019-10-25T19:33:43" hostname="localhost" time="14.656" errors="0" tests="6" skipped="0" disabled="0" failures="0">
  <testcase classname="PO special instruction" name="Open PO Special instruction module" time="1.274" />
  <testcase classname="PO special instruction" name="verify that search and facility fiter with search and add button appear on the page" time="0.171" />
  <testcase classname="PO special instruction" name="add new instruction" time="2.149" />
  <testcase classname="PO special instruction" name="search newly created instruction by name" time="2.745" />
  <testcase classname="PO special instruction" name="update the newly special instruction" time="4.834" />
  <testcase classname="PO special instruction" name="delete newly created special instruction" time="3.483" />
 </testsuite>
 <testsuite name="Price Tier Setup module" timestamp="2019-10-25T19:33:57" hostname="localhost" time="43.114" errors="0" tests="9" skipped="0" disabled="0" failures="0">
  <testcase classname="Price Tier Setup module" name="Open Price Tier Setup module" time="0.944" />
  <testcase classname="Price Tier Setup module" name="verify that search filter appear on price tier setup listing page" time="0.11" />
  <testcase classname="Price Tier Setup module" name="Verify that user is able to add new price tier" time="7.431" />
  <testcase classname="Price Tier Setup module" name="Search newly created price tier by name" time="0.6" />
  <testcase classname="Price Tier Setup module" name="set newly created price tier with vendor" time="14.853" />
  <testcase classname="Price Tier Setup module" name="verify that user is not able to delete mapped price tier" time="4.659" />
  <testcase classname="Price Tier Setup module" name="add a new price tier to check edit and delete functionality" time="5.607" />
  <testcase classname="Price Tier Setup module" name="verify that user is able to edit and update newly edit price tier" time="4.362" />
  <testcase classname="Price Tier Setup module" name="verify that user is able to delete newly created price tier" time="4.546" />
 </testsuite>
 <testsuite name="Print Barcodes/QRCodes" timestamp="2019-10-25T19:34:41" hostname="localhost" time="14.471" errors="0" tests="6" skipped="0" disabled="0" failures="1">
  <testcase classname="Print Barcodes/QRCodes" name="Open Print Barcodes/QRCodes module" time="1.571" />
  <testcase classname="Print Barcodes/QRCodes" name="verify that search and status filter appear on the page" time="0.2" />
  <testcase classname="Print Barcodes/QRCodes" name="search item by description" time="4.627" />
  <testcase classname="Print Barcodes/QRCodes" name="search item by alias" time="4.127" />
  <testcase classname="Print Barcodes/QRCodes" name="search item by sku" time="3.87" />
  <testcase classname="Print Barcodes/QRCodes" name="verify that all option to print item are availbale under print code button" time="0.075">
   <failure type="exception" message="Failed: No element found using locator: By(xpath, //button[@class=&quot;btn btn-default no-margin&quot;])"><![CDATA[NoSuchElementError: No element found using locator: By(xpath, //button[@class="btn btn-default no-margin"])
    at elementArrayFinder.getWebElements.then (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:814:27)
    at ManagedPromise.invokeCallback_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
    at process._tickCallback (internal/process/next_tick.js:68:7)Error
    at ElementArrayFinder.applyAction_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:459:27)
    at ElementArrayFinder.(anonymous function).args [as click] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:91:29)
    at ElementFinder.(anonymous function).args [as click] (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\built\element.js:831:22)
    at UserContext.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\PrintBarcode_qrcode.js:54:71)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
    at new ManagedPromise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
    at ControlFlow.promise (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
    at schedulerExecute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
From: Task: Run it("verify that all option to print item are availbale under print code button") in control flow
    at UserContext.<anonymous> (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:19)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at QueueRunner.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4199:10)
    at Spec.queueRunnerFactory (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:909:35)
    at Spec.execute (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:526:10)
    at UserContext.fn (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:5340:37)
    at attempt (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at runNext (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)
From asynchronous test: 
Error
    at Suite.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\PrintBarcode_qrcode.js:53:3)
    at addSpecsToSuite (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
    at Env.describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
    at describe (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
    at Object.<anonymous> (F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\PrintBarcode_qrcode.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)]]>
   </failure>
  </testcase>
 </testsuite>
 <testsuite name="Stock Adjustment Notes" timestamp="2019-10-25T19:34:55" hostname="localhost" time="1.811" errors="0" tests="2" skipped="0" disabled="0" failures="0">
  <testcase classname="Stock Adjustment Notes" name="Open Stock Adjustment Notes module" time="1.571" />
  <testcase classname="Stock Adjustment Notes" name="verify that search and status filter appear on the page" time="0.239" />
 </testsuite>
 <testsuite name="UOU Management" timestamp="2019-10-25T19:34:57" hostname="localhost" time="2.009" errors="0" tests="3" skipped="0" disabled="0" failures="1">
  <testcase classname="UOU Management" name="Open UOU Management module" time="1.536" />
  <testcase classname="UOU Management" name="verify that search and status filter appear on the page" time="0.197" />
  <testcase classname="UOU Management" name="verify all consumption type appear under the consumption type dropdown" time="0.275">
   <failure type="toContain" message="Expected [ &apos;All&apos;, &apos;Piece&apos;, &apos;Length&apos;, &apos;Weight&apos;, &apos;Liquid&apos;, &apos;Drops&apos;, &apos;Sprays&apos; ] to contain [ &apos;All&apos;, &apos;Piece&apos;, &apos;Length&apos;, &apos;Weight&apos;, &apos;Liquid&apos;, &apos;Drops&apos;, &apos;Sprays&apos; ]."><![CDATA[Error: Failed expectation
    at F:\protractor\Hybrent3.2\Hybrent3.2\Testcases\Admin_section\UOU_Management.js:28:24
    at ManagedPromise.invokeCallback_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
    at C:\Users\sandy\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
    at process._tickCallback (internal/process/next_tick.js:68:7)]]>
   </failure>
  </testcase>
 </testsuite>
 <testsuite name="Utilities" timestamp="2019-10-25T19:34:59" hostname="localhost" time="42.577" errors="0" tests="15" skipped="0" disabled="0" failures="0">
  <testcase classname="Utilities" name="Open Utilities module" time="1.487" />
  <testcase classname="Utilities" name="verify that search filter appear on the utilities page" time="0.189" />
  <testcase classname="Utilities" name="search import facility utitilites by its name" time="2.924" />
  <testcase classname="Utilities" name="search import department utitilites by its name" time="3.172" />
  <testcase classname="Utilities" name="search import_inventories utitilites by its name" time="3.238" />
  <testcase classname="Utilities" name="search import_users utitilites by its name" time="3.129" />
  <testcase classname="Utilities" name="search syncmap_item utitilites by its name" time="3.397" />
  <testcase classname="Utilities" name="search template utitilites by its name" time="3.06" />
  <testcase classname="Utilities" name="search template utitilites by its name" time="3.159" />
  <testcase classname="Utilities" name="search Change_temp_owner utitilites by its name" time="3.21" />
  <testcase classname="Utilities" name="search Assign_remove_vendor_access utitilites by its name" time="3.084" />
  <testcase classname="Utilities" name="search Download_user_facilities_access utitilites by its name" time="3.215" />
  <testcase classname="Utilities" name="search Download_user_approval_access utitilites by its name" time="3.113" />
  <testcase classname="Utilities" name="search Assign_user_facility_access utitilites by its name" time="3.139" />
  <testcase classname="Utilities" name="search Remove_user_facility_access utitilites by its name" time="3.061" />
 </testsuite>
 <testsuite name="Vendors Account Setup module" timestamp="2019-10-25T19:35:41" hostname="localhost" time="15.414" errors="0" tests="4" skipped="0" disabled="0" failures="0">
  <testcase classname="Vendors Account Setup module" name="Open Vendors Account Setup module" time="0.705" />
  <testcase classname="Vendors Account Setup module" name="select vendor by select vendor list and verify the account number of user default facility" time="10.036" />
  <testcase classname="Vendors Account Setup module" name="verify that on clicking save button user get redirect to back page with updation toast message" time="2.247" />
  <testcase classname="Vendors Account Setup module" name="Verify that on clicking close button user get redirect to Dashboard page" time="2.426" />
 </testsuite>
 <testsuite name="Vendor module" timestamp="2019-10-25T19:35:57" hostname="localhost" time="6.159" errors="0" tests="3" skipped="0" disabled="0" failures="0">
  <testcase classname="Vendor module" name="Open vendor module" time="1.046" />
  <testcase classname="Vendor module" name="verify that search filter appear on the vendor listing page" time="0.227" />
  <testcase classname="Vendor module" name="search vendor by vendor name" time="4.886" />
 </testsuite>
 <testsuite name="Hybrent DME Module" timestamp="2019-10-25T19:36:03" hostname="localhost" time="26.952" errors="0" tests="2" skipped="0" disabled="0" failures="0">
  <testcase classname="Hybrent DME Module" name="navigate to start new claim page" time="2.349" />
  <testcase classname="Hybrent DME Module" name="click on select button to select patient to generate a claim" time="24.602" />
 </testsuite>
</testsuites>